// English defaults for the renderer's and designer's UI labels. Add a key here first; dv.json holds the Dhivehi translations.
// Substitution is {name} only.
export const en = {
  "action.cancel": "Cancel",
  "admin.dragToReorder": "Drag to reorder, or press Space and use the arrow keys",
  "common.no": "No",
  "common.yes": "Yes",
  "designer.acceptedTypes": "Accepted file types",
  "designer.acceptedTypesHelp": "MIME types, for example application/pdf.",
  "designer.addARule": "Add a rule",
  "designer.addAnotherRule": "Add another rule",
  "designer.addArgument": "Add argument",
  "designer.addBusinessRule": "Add business rule",
  "designer.addDateField": "Add a date field to calculate from.",
  "designer.addGroupFirst": "Add a repeated group to the form before counting its items.",
  "designer.addMessage": "Add message",
  "designer.addNumberField": "Add a number or amount field to calculate from.",
  "designer.addOption": "Add option",
  "designer.addPage": "Add page",
  "designer.addRelated": "Add related line",
  "designer.allSaved": "All changes saved",
  "designer.andMore": "and {count} more.",
  "designer.andMoreInRequest": "and {count} more, listed in the change request.",
  "designer.applicantNid": "Applicant's National ID (self.nid)",
  "designer.appliesWhen": "Applies when",
  "designer.approveAndPublish": "Approve and publish",
  "designer.approveBlocked": "{count} business rules are not implemented yet ({ids}), so this version cannot be approved",
  "designer.approveBlockedOne": "1 business rule is not implemented yet ({ids}), so this version cannot be approved",
  "designer.approveText": "This records your approval as the developer and publishes the version. Every business rule in it has an implementation, so it runs as designed. After this it can be chosen in rounds.",
  "designer.approveTitle": "Approve and publish version {version}?",
  "designer.archivedToast": "Version {version} archived",
  "designer.argumentAria": "Argument {number}",
  "designer.argumentIsAria": "Argument {number} is",
  "designer.atLeast": "At least",
  "designer.atMost": "At most",
  "designer.backInDraft": "Version {version} returned to draft. It can be edited again.",
  "designer.backToForms": "Back to forms",
  "designer.blocking": "Blocking",
  "designer.breakHelp": "A horizontal line between sections. It has no settings besides when it is shown.",
  "designer.businessRuleAria": "Business rule {number}",
  "designer.businessRulePlaceholder": "For example: the requested amount must not be more than the scheme's limit",
  "designer.businessRules": "Business rules",
  "designer.businessRulesHelp": "Describe checks the form cannot express with settings, such as comparing answers or asking another system. A developer implements each rule before the form is published.",
  "designer.canvasAria": "Form canvas",
  "designer.canvasView": "Canvas view",
  "designer.changeRequestCopied": "Change request copied",
  "designer.changeRequestIntro": "Send this to the developer. It lists what changed since the last published version, the business rules to implement and the full definition.",
  "designer.changeRequestTitle": "Change request for the developer",
  "designer.changesForDeveloper": "Changes for the developer",
  "designer.checkResultOf": "{label}: check result",
  "designer.chooseConnector": "Choose a connector",
  "designer.chooseField": "Choose a field",
  "designer.chooseGroup": "Choose a repeated group",
  "designer.chooseSource": "Choose a source",
  "designer.chooseValue": "Choose a value",
  "designer.chooseValues": "Choose values",
  "designer.clickAddsNewRow": "Click or press Enter to add a new fields row at the end of the page. Press Space to drag.",
  "designer.clickAddsToRow": "Click or press Enter to add to the selected row. Press Space to drag.",
  "designer.combineAria": "Combine rules",
  "designer.computedName": "Computed field '{key}'",
  "designer.condAtLeast": "is at least",
  "designer.condAtMost": "is at most",
  "designer.condEmpty": "is empty",
  "designer.condEquals": "is",
  "designer.condGreaterThan": "is more than",
  "designer.condIn": "is one of",
  "designer.condLessThan": "is less than",
  "designer.condNotEmpty": "is not empty",
  "designer.condNotEquals": "is not",
  "designer.condNotIn": "is none of",
  "designer.conditionAria": "Condition",
  "designer.connector": "Connector",
  "designer.copy": "Copy",
  "designer.copyBlocked": "The browser blocked copying. Select the text and copy it by hand.",
  "designer.copyJson": "Copy JSON",
  "designer.countNeedsFields": "Add fields to the repeated group before choosing which items to count.",
  "designer.countOnlyWhere": "Count only items where",
  "designer.defaultGroupLabel": "Group",
  "designer.defaultItemLabel": "Item",
  "designer.defaultOption": "Option {number}",
  "designer.delete": "Delete",
  "designer.deleteField": "Delete field",
  "designer.deletePage": "Delete page",
  "designer.deletePageFields": "This also deletes its {count} fields.",
  "designer.deletePageFieldsOne": "This also deletes its 1 field.",
  "designer.deletePageNoFields": "The page has no fields.",
  "designer.deletePageTitle": "Delete page {name}?",
  "designer.deleteRow": "Delete row",
  "designer.deleteRowNamed": "Delete {name}",
  "designer.describeCheckResult": "{name} check result",
  "designer.describeNot": "not ({condition})",
  "designer.describeQuantified": "{match} {item} has {rest}",
  "designer.downloadFile": "Download file",
  "designer.draftSaved": "Draft saved",
  "designer.dragCancelled": "Moving {name} was cancelled.",
  "designer.dragDropped": "{name} was dropped on {target}.",
  "designer.dragDroppedNowhere": "{name} was dropped where it cannot go, so nothing changed.",
  "designer.dragInstructions": "To move this item, press Space, then use the arrow keys. Press Space or Enter to drop it, or Escape to cancel.",
  "designer.dragNotOver": "{name} is not over a place it can be dropped.",
  "designer.dragOver": "{name} is over {target}.",
  "designer.dragPickedUp": "Picked up {name}.",
  "designer.dragRow": "Drag {name} to reorder",
  "designer.emptyRow": "Drop a field here, or select this row and click a field type.",
  "designer.emptyTextRow": "Empty {type}",
  "designer.endOfPage": "the end of the page",
  "designer.endZone": "Drop here to add at the end of the page",
  "designer.everyItem": "{label}, every {item} ({key})",
  "designer.everyItemCounted": "Every item is counted.",
  "designer.exportChangeRequest": "Export change request",
  "designer.exportJson": "Export JSON",
  "designer.externalSystem": "External system",
  "designer.failureContactAdmin": "{reason} Contact Admin",
  "designer.fewestChars": "Fewest characters",
  "designer.field": "Field",
  "designer.fieldAlwaysShown": "This field is always shown.",
  "designer.fieldHeading": "{type} field",
  "designer.fieldKeyHelp": "Answers are stored under this key. Keep it short, in camelCase.",
  "designer.fieldKeyInvalid": "Key '{key}' must start with a lowercase letter and use only letters and numbers, for example monthlyIncome",
  "designer.fieldKeyTaken": "Field key '{key}' is already used on page {page}",
  "designer.fieldLabelHelp": "The question people see.",
  "designer.fieldPositionHelp": "Moves the field without dragging.",
  "designer.fields": "Fields",
  "designer.fieldsRowHelp": "Fields in this row sit side by side. Set each field's width to control how much room it takes.",
  "designer.formLanguage": "Show the form in",
  "designer.formTitleAria": "Form title",
  "designer.formatChecked": "The format of this type is checked automatically.",
  "designer.formsTitle": "Forms",
  "designer.formula": "Formula",
  "designer.formulaAge": "Age in whole years from a date (AGE)",
  "designer.formulaAtLeast": "{name}: {fn} needs at least {count} arguments",
  "designer.formulaColumnOnlySum": "{name}: only SUM and COUNT can use a column of a repeated group such as '{arg}'",
  "designer.formulaCount": "Count items in a group (COUNT)",
  "designer.formulaCountNeedsGroup": "{name}: COUNT needs a repeated group, and '{arg}' is not one",
  "designer.formulaDaysBetween": "Days from the first date to the second (DAYS_BETWEEN)",
  "designer.formulaDifference": "Subtract from the first (DIFFERENCE)",
  "designer.formulaDivide": "Divide the first by the second (DIVIDE)",
  "designer.formulaEmptyArg": "{name} has an empty argument. Pick a field or enter a number",
  "designer.formulaExact": "{name}: {fn} needs exactly {count} arguments",
  "designer.formulaExactOne": "{name}: {fn} needs exactly 1 argument",
  "designer.formulaHelp": "The value is calculated from other answers and shown read only. It updates as people type.",
  "designer.formulaMissing": "{name} has no formula. Choose a function and the fields it calculates from",
  "designer.formulaNotField": "{name} refers to '{arg}', which is not a field in this form. Pick an existing field",
  "designer.formulaNotGroupColumn": "{name} refers to '{arg}', which is not a field in a repeated group of this form",
  "designer.formulaProduct": "Multiply (PRODUCT)",
  "designer.formulaSum": "Add up (SUM)",
  "designer.function": "Function",
  "designer.givesBack": "Gives back: {outputs}. Use these in rules and messages.",
  "designer.groupKey": "Group key",
  "designer.groupKeyHelp": "Answers are stored as a list under this key.",
  "designer.groupKeyInvalid": "Key '{key}' must start with a lowercase letter and use only letters and numbers, for example coApplicants",
  "designer.groupKeyTaken": "Key '{key}' is already used by another field or group",
  "designer.groupLabel": "Group label",
  "designer.groupLabelHelp": "Heading shown above the group.",
  "designer.groupToCount": "Group to count",
  "designer.helpText": "Help text",
  "designer.helpTextHelp": "Shown under the label.",
  "designer.howManyItems": "How many items",
  "designer.implemented": "Implemented",
  "designer.import": "Import",
  "designer.importAria": "Form definition JSON",
  "designer.importIntro": "Paste a form definition. It replaces the pages in this version. The key and version number stay as they are.",
  "designer.importJson": "Import JSON",
  "designer.imported": "JSON imported. Use Undo to go back to the previous content.",
  "designer.inDhivehi": "{label} in Dhivehi",
  "designer.inGroup": "{label} (in {group})",
  "designer.inputMapping": "Input mapping",
  "designer.issueFieldCondition": "The condition for field '{key}'",
  "designer.issueFormulaLoop": "Computed fields {keys} depend on each other in a loop. Change one formula so it no longer depends on itself",
  "designer.issueInputUnmapped": "Field '{key}' on page {page} does not say where the connector input '{input}' comes from. Map it to a field or the applicant's National ID",
  "designer.issueMessageCondition": "A message on field '{key}'",
  "designer.issueMessageNoText": "A message on field '{key}' has no text. Enter the text or delete the message",
  "designer.issueMissingField": "{what} on page {page} refers to '{key}', which is not a field in this form. Pick an existing field or remove the condition",
  "designer.issueNoConnector": "Field '{key}' on page {page} has no connector. Choose the external system to look up",
  "designer.issueNoLabel": "Field '{key}' on page {page} has no label. Enter the label people filling in the form will see",
  "designer.issueNoOptions": "Field '{key}' on page {page} has no options. Add options or choose a list",
  "designer.issueNoPages": "Add at least one page",
  "designer.issueNoTitle": "Enter a form title",
  "designer.issuePageCondition": "The condition for the page",
  "designer.issuePageKey": "Page key '{key}' must start with a lowercase letter and use only letters and numbers",
  "designer.issuePageKeyTwice": "Page key '{key}' is used by more than one page. Give each page its own key",
  "designer.issuePageNoTitle": "Page {number} has no title. Enter the title people filling in the form will see",
  "designer.issueRepeated": "Repeated group: {problem}",
  "designer.issueRowCondition": "The condition for a row",
  "designer.issueRowNoText": "A {row} on page {page} has no text. Enter the text or delete the row",
  "designer.issueRuleNoText": "A business rule on field '{key}' has no description. Describe what the rule checks, or remove it",
  "designer.item": "item",
  "designer.itemLabel": "Item label",
  "designer.itemLabelHelp": "Names each repeat, for example Co-applicant.",
  "designer.joinAnd": "and",
  "designer.joinOr": "or",
  "designer.jsonCopied": "JSON copied",
  "designer.jsonEmpty": "No answers yet. Answer questions in Live preview and they show here.",
  "designer.jsonFieldType": "{at}: type '{type}' is not a field type. Use one of {types}",
  "designer.jsonMustBeList": "{at}: '{prop}' must be a list",
  "designer.jsonMustBeText": "{at}: '{prop}' must be text",
  "designer.jsonNotObject": "The JSON must be an object with key, title and pages",
  "designer.jsonOptionsList": "{at}: 'options' must be a list of value and label",
  "designer.jsonPagesEmpty": "'pages' has no pages. Add at least one",
  "designer.jsonPagesList": "'pages' must be a list of pages",
  "designer.jsonRepeatType": "{at}: 'repeatType' must be 'fixed' or 'add'",
  "designer.jsonRootText": "'{prop}' must be text",
  "designer.jsonRowType": "{at}: type '{type}' is not a row type. Use one of {types}",
  "designer.keepEditing": "Keep editing",
  "designer.keepPage": "Keep page",
  "designer.keyEmpty": "Enter a key, for example monthlyIncome. Answers are stored under this key",
  "designer.labelDescription": "Description",
  "designer.labelKey": "Key",
  "designer.labelLabel": "Label",
  "designer.labelText": "Text",
  "designer.labelTitle": "Title",
  "designer.labelType": "Type",
  "designer.largestAllowed": "Largest allowed",
  "designer.largestFile": "Largest file (MB)",
  "designer.leaveCancel": "Stay and keep editing",
  "designer.leaveConfirm": "Leave and discard changes",
  "designer.leaveText": "This draft has changes that are not saved. If you leave now they are lost.",
  "designer.leaveTitle": "Leave without saving?",
  "designer.limits": "Limits",
  "designer.list": "List",
  "designer.lookupError": "Check failed",
  "designer.lookupFound": "Record found",
  "designer.lookupNotFound": "No record found",
  "designer.lookupPending": "Still checking",
  "designer.matchAll": "every",
  "designer.matchAny": "any",
  "designer.matchNone": "no",
  "designer.messagePlaceholder": "What the person should read, and what to do about it",
  "designer.messageTextAria": "Message text",
  "designer.messageWhenEmpty": "Add a rule to say when this message appears.",
  "designer.messages": "Messages",
  "designer.messagesHelp": "Show a message under the field when a rule matches. A blocking message stops the person from going to the next page.",
  "designer.modeAll": "all rules match",
  "designer.modeAny": "any rule matches",
  "designer.mostChars": "Most characters",
  "designer.mostFiles": "Most files",
  "designer.moveEarlier": "Move earlier",
  "designer.moveLater": "Move later",
  "designer.moveLeft": "Move left",
  "designer.moveRight": "Move right",
  "designer.moveRowDown": "Move {name} down",
  "designer.moveRowUp": "Move {name} up",
  "designer.moveToRowAbove": "Move to row above",
  "designer.moveToRowBelow": "Move to row below",
  "designer.mustBeTicked": "Must be ticked",
  "designer.mustBeTickedHelp": "For declarations the person has to accept.",
  "designer.narrowText": "Open this page on a screen at least 1000 pixels wide to edit the form. Here is the read-only JSON of this version.",
  "designer.narrowTitle": "The designer needs a wider screen",
  "designer.nestedText": "This condition is nested more deeply than the builder can edit. Edit it through Import JSON, or replace it with simple rules.",
  "designer.newRowHere": "a new fields row here",
  "designer.newVersion": "New version",
  "designer.noFormulaYet": "No formula yet",
  "designer.noPrefill": "Do not prefill",
  "designer.noValueNeeded": "No value needed",
  "designer.notAField": "'{path}' is not a field in this form. Choose another field.",
  "designer.notFoundText": "It may have been deleted. Go back to the forms list and open another version.",
  "designer.notFoundTitle": "This form version was not found",
  "designer.notJson": "The text is not valid JSON: {error}",
  "designer.notSaved": "The form was not saved",
  "designer.notTicked": "Not ticked",
  "designer.number": "Number",
  "designer.numberOfItems": "Number of items",
  "designer.onePageText": "This is the only page, so it cannot be deleted. Add another page first, or edit this one.",
  "designer.onePageTitle": "A form needs one page",
  "designer.openAwaitingVersion": "Open version {version} (awaiting developer)",
  "designer.openDraftVersion": "Open draft version {version}",
  "designer.optionLabelAria": "Label of option {number}",
  "designer.optionValueAria": "Value of option {number}",
  "designer.optionValueTwice": "Value '{value}' is used twice",
  "designer.options": "Options",
  "designer.optionsList": "Use a list",
  "designer.optionsOwn": "Type the options",
  "designer.optionsSourceAria": "Where options come from",
  "designer.page": "Page",
  "designer.pageAlwaysShown": "This page is always shown.",
  "designer.pageDescriptionHelp": "Shown under the page title.",
  "designer.pageKeyHelp": "Used in the page's address and in saved answers.",
  "designer.pageKeyInvalid": "Key '{key}' must start with a lowercase letter and use only letters and numbers, for example household",
  "designer.pageKeyTaken": "Page key '{key}' is already used by another page",
  "designer.pageNumber": "Page {number}",
  "designer.pagePosition": "Page {number} of {total}. Moves the page without dragging its tab.",
  "designer.pageProperties": "Page properties",
  "designer.pagesAria": "Pages",
  "designer.paletteAria": "Rows and fields to add",
  "designer.pattern": "Pattern",
  "designer.patternHelp": "A regular expression the answer must match, for example ^[A-Z]{2}\\d{4}$.",
  "designer.placeholder": "Placeholder",
  "designer.placeholderLabel": "Label",
  "designer.placeholderValue": "Value",
  "designer.position": "Position",
  "designer.prefill": "Prefill",
  "designer.previewRules": "Implemented business rules run here. {count} requested rules do not run until a developer implements them: {rules}.",
  "designer.previewRulesOne": "Implemented business rules run here. 1 requested rule does not run until a developer implements it: {rules}.",
  "designer.previewSaved": "Preview draft saved. Nothing was stored.",
  "designer.previewSubmitted": "Preview submitted. Nothing was stored.",
  "designer.problemsBeforeImport": "{count} problems to fix before importing",
  "designer.problemsBeforeImportOne": "1 problem to fix before importing",
  "designer.problemsBeforePublish": "{count} problems to fix before publishing",
  "designer.problemsBeforePublishOne": "1 problem to fix before publishing",
  "designer.problemsBlockPublish": "These block publishing. Saving a draft is still allowed.",
  "designer.problemsToFix": "{count} problems to fix",
  "designer.problemsToFixOne": "1 problem to fix",
  "designer.propertiesAria": "Properties",
  "designer.publish": "Publish",
  "designer.publishImmutable": "Publishing makes this version immutable. After that it can be chosen in rounds, and changes need a new version.",
  "designer.publishNoChanges": "Nothing changed since the last published version.",
  "designer.publishTitle": "Publish version {version}?",
  "designer.publishVersion": "Publish version",
  "designer.publishWordingOnly": "Only wording, order and layout changed since the last published version, so you can publish without a developer.",
  "designer.publishedToast": "Version {version} published. It can now be chosen in rounds.",
  "designer.readOnly": "Read only",
  "designer.readOnlyArchived": "This version is archived, so it cannot be edited. Open the latest version to make changes.",
  "designer.readOnlyAwaitingDev": "This version is waiting for a developer to check its changes and implement its business rules, so it cannot be edited. Return it to draft to change it.",
  "designer.readOnlyHelp": "Shown but not editable, for example a prefilled name.",
  "designer.readOnlyPublished": "This version is published, so it cannot be edited. Start a new version to make changes.",
  "designer.relatedHelp": "Shows a line under the field after a choice, such as the council of an island.",
  "designer.relatedLabelAria": "Related label",
  "designer.relatedLabelPlaceholder": "Label, for example Council",
  "designer.relatedPropertyAria": "Related property",
  "designer.relatedPropertyPlaceholder": "Property",
  "designer.relatedTitle": "Show related information",
  "designer.removeArgument": "Remove argument {number}",
  "designer.removeMessage": "Remove message",
  "designer.removeOption": "Remove option {number}",
  "designer.removeRelated": "Remove related information",
  "designer.removeRule": "Remove rule",
  "designer.repeatAdd": "People add items",
  "designer.repeatAnyNumber": "Add any number",
  "designer.repeatAtLeast": "At least {count}.",
  "designer.repeatFixed": "Fixed at {count} items",
  "designer.repeatFixedNumber": "Fixed number",
  "designer.repeatFixedOne": "Fixed at 1 item",
  "designer.repeatTypeAria": "Repeat type",
  "designer.repeatUpTo": "Add up to {count}",
  "designer.replaceSimple": "Replace with simple rules",
  "designer.requested": "Requested",
  "designer.required": "Required",
  "designer.requiredAria": "required",
  "designer.returnToDraft": "Return to draft",
  "designer.row": "Row",
  "designer.rowAlwaysShown": "This row is always shown.",
  "designer.rowBreak": "Section break",
  "designer.rowFields": "Fields row",
  "designer.rowHeading": "Heading",
  "designer.rowParagraph": "Paragraph",
  "designer.rowRepeated": "Repeated group",
  "designer.rowSubheading": "Subheading",
  "designer.rows": "Rows",
  "designer.rulesImplemented": "{count} rules implemented",
  "designer.rulesImplementedOne": "1 rule implemented",
  "designer.rulesNeedFields": "Add at least one field to the form before writing rules.",
  "designer.rulesRequested": "{count} rules requested",
  "designer.rulesRequestedOne": "1 rule requested",
  "designer.rulesToImplement": "{count} business rules need to be implemented. Use Export change request to send the details.",
  "designer.rulesToImplementOne": "1 business rule needs to be implemented. Use Export change request to send the details.",
  "designer.saveDraft": "Save draft",
  "designer.sendChangedText": "This version changes more than wording, so a developer checks it before it is published. It stays locked while it waits; you can return it to draft at any time.",
  "designer.sendFirstText": "This is the first version of the form, so a developer checks it before it is published. It stays locked while it waits; you can return it to draft at any time.",
  "designer.sendTitle": "Send version {version} to the developer?",
  "designer.sendToDeveloper": "Send to developer",
  "designer.sentToDeveloper": "Version {version} sent to the developer. It stays locked until the developer approves it or it is returned to draft.",
  "designer.showResultAs": "Show the result as",
  "designer.shownWhen": "Shown when {condition}",
  "designer.shownWhenSection": "Shown when",
  "designer.smallestAllowed": "Smallest allowed",
  "designer.sourceOf": "Source of {input}",
  "designer.sourcesHelp": "Sources are the applicant's National ID or another field in the same row.",
  "designer.statusArchived": "Archived",
  "designer.statusAwaitingDev": "Awaiting developer",
  "designer.statusDraft": "Draft",
  "designer.statusPublished": "Published",
  "designer.thisField": "this field",
  "designer.ticked": "Ticked",
  "designer.title": "Form designer",
  "designer.toneAria": "Tone",
  "designer.toneError": "Error",
  "designer.toneInfo": "Information",
  "designer.toneSuccess": "Confirmation",
  "designer.toneWarning": "Warning",
  "designer.typeAmount": "Amount",
  "designer.typeCheckbox": "Checkbox",
  "designer.typeComputed": "Computed (formula)",
  "designer.typeDate": "Date",
  "designer.typeDropdown": "Dropdown",
  "designer.typeEmail": "Email address",
  "designer.typeFile": "File upload",
  "designer.typeLongText": "Long text",
  "designer.typeLookup": "Lookup (external system)",
  "designer.typeMultipleChoice": "Multiple choice",
  "designer.typeNationalId": "National ID",
  "designer.typeNumber": "Number",
  "designer.typePhone": "Phone number",
  "designer.typeRadio": "Single choice (radio)",
  "designer.typeShortText": "Short text",
  "designer.typeValuePlaceholder": "Type a value and press Enter",
  "designer.undo": "Undo",
  "designer.undoHint": "You can undo this straight afterwards with Undo.",
  "designer.unsavedChanges": "Unsaved changes",
  "designer.untitledField": "Untitled field",
  "designer.untitledPage": "Untitled page",
  "designer.useAutoWidth": "Use automatic width",
  "designer.valueAria": "Value",
  "designer.valuesAria": "Values",
  "designer.versionNumber": "Version {version}",
  "designer.viewDesign": "Design",
  "designer.viewJson": "JSON",
  "designer.viewLive": "Live preview",
  "designer.viewStatic": "Static preview",
  "designer.whenMatch": "When {match} {item}",
  "designer.whichItems": "Which items",
  "designer.width": "Width in the row",
  "designer.widthAuto": "Automatic",
  "designer.widthOf": "{width} of 12",
  "wizard.addItem": "Add {item}",
  "wizard.back": "Back",
  "wizard.backToAnswers": "Back to your answers",
  "wizard.cantContinue": "You can’t continue: {reason}",
  "wizard.cantSubmit": "You can’t submit: {reason}",
  "wizard.checkAgain": "Check again",
  "wizard.chooseOne": "Choose one",
  "wizard.dropFile": "Drop a file here or choose from your device",
  "wizard.dropFiles": "Drop files here or choose from your device",
  "wizard.fieldToFix": "1 field to fix",
  "wizard.fieldsToFix": "{count} fields to fix",
  "wizard.fileLimits": "{types}, up to {size} MB each",
  "wizard.fileLimitsCount": "{types}, up to {size} MB each, up to {count} files",
  "wizard.fileNotAdded": "{name} could not be added: {reason}",
  "wizard.fileTooLarge": "{name} is {size} MB. The limit is {limit} MB, so choose a smaller file.",
  "wizard.fileWrongType": "{name} is not an accepted file type. Upload {types}.",
  "wizard.filesFull": "You have attached the most files allowed here ({count}). Remove one to add another.",
  "wizard.fixIntro": "Fix the fields marked below, then send your corrections. Everything else is locked.",
  "wizard.fixRequested": "You were asked to fix this",
  "wizard.item": "Item",
  "wizard.itemNumber": "(item {number})",
  "wizard.lookupError": "The check could not be completed",
  "wizard.lookupFailed": "The registry did not answer. Check the details above, then check again. If it keeps failing, Contact Admin.",
  "wizard.lookupFound": "Record found",
  "wizard.lookupNotConfigured": "{connector} can't be checked because no lookup service is set up for this app. Contact Admin.",
  "wizard.lookupNotFound": "No record found",
  "wizard.lookupPending": "Checking the registry",
  "wizard.lookupRecord": "Record {ref}",
  "wizard.lookupWaiting": "Fill in the details above and the check runs by itself.",
  "wizard.maxItems": "You can add up to {max}.",
  "wizard.next": "Next",
  "wizard.noItems": "No {item} added yet.",
  "wizard.noRecord": "No record",
  "wizard.notCalculated": "Not calculated yet",
  "wizard.notChecked": "Not checked yet",
  "wizard.notEligibleTitle": "You are not eligible to apply",
  "wizard.notProvided": "Not provided",
  "wizard.onPage": "on {page}",
  "wizard.pickDate": "Pick a date",
  "wizard.problemOne": "There is a problem on this page",
  "wizard.problems": "There are {count} problems on this page",
  "wizard.remove": "Remove",
  "wizard.removeFile": "Remove {name}",
  "wizard.removeItem": "Remove {item} {number}",
  "wizard.reviewerAsked": "{by} asked you to fix this",
  "wizard.saveDraft": "Save draft",
  "wizard.savedAt": "Saved at {time}",
  "wizard.stepCount": "Step {current} of {total}",
  "wizard.steps": "Form steps",
  "wizard.submit": "Submit",
  "wizard.tooManyFiles": "You can attach {count} file(s) here. Remove one before adding another.",
  "wizard.unsavedChanges": "Unsaved changes. Last saved at {time}",
  "wizard.uploading": "Uploading {name}",
}
